version: "3"
# Define the services/containers to be run
services:
  database-auth: # name of the service
    image: mongo # specify image to build container from
    # command: mongod --port 64315
    ports:
      - "27015:27017" # specify port forewarding
    volumes:
      - authDB:/data/authDB

  database-notify: # name of the service
    image: mongo # specify image to build container from
    # command: mongod --port 64315
    ports:
      - "27016:27017" # specify port forewarding
    volumes:
      - notifyDB:/data/notifyDB      

  front-end: # name of the service
    build: ./frontend/grades # specify the directory of the Dockerfile
    ports:
      - "4200:80" # specify port forewarding
    links:
      - auth # link this service to the server service
      - notify # link this service to the server service

  auth: #name of the service
    build: ./backend/auth # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database-auth # link this service to the database service
      
  notify: #name of the service
    build: ./backend/notify # specify the directory of the Dockerfile
    ports:
      - "3001:3001" #specify ports forewarding
    links:
      - database-notify # link this service to the database service
volumes:
  authDB:
  notifyDB:      